struct node3
{
	double pos,s,e;
}x,y;
struct node4
{
	double sx,sy,ex,ey;
}x_45,x_135;
void maketable()
{
    int i,j,k,sp,m,flag,cc;
	double x1,x2,y1,y2,fx,fy,midx,midy,p,q,crop,cro_point[2][2];
	double l,r,t,b;
	for(i=1;i<=vertice;i++)
	{
		for(k=0;k<4;k++){
           records1[i].c[k]=0;
		   records1[i].semiperimeter[k]=0;}
	}
	for(i=1;i<=vertice-1;i++)
	{
	   for(sp=0;sp<=3;sp++)
	   {
			  x1=graph[edge[i].s][0];
		      y1=graph[edge[i].s][1];
		      x2=graph[edge[i].e][0];
		      y2=graph[edge[i].e][1];
		      fx=fabs(x1-x2);
		      fy=fabs(y1-y2);
			  m=sp;
			  x.pos=-1;x.s=-1;x.e=-1;
              y.pos=-1;y.s=-1;y.e=-1;
			  x_45.sx=999999999;x_45.sy=999999999;x_45.ex=999999999;x_45.ey=999999999;
              x_135.sx=999999999;x_135.sy=999999999;x_135.ex=999999999;x_135.ey=999999999;
			 if(x1<x2) 
			  {
				  l=x1;
				  r=x2;
			  }
			  else
			  {
				  l=x2;
				  r=x1;
			  }
			  if(y1<y2)
			  {
				  b=y1;
				  t=y2;
			  }
			  else
			  {
				  b=y2;
				  t=y1;
			  }
			  if(m==0||m==1) 
			  {
                  if(fx==0||fy==0) 
				  { 
			         if(m==0)
					 {
                        x.pos=y1; 
				        y.pos=x1;
					 }
			         else
					 {
				        x.pos=y2;
				        y.pos=x2;
					 }
			   	     if(x1>x2)
					 {
				        x.s=x2; 
				        x.e=x1; 
					 }
			         else
					 {
                       x.s=x1;
				       x.e=x2;
					 }
			        if(y1>y2)
					{
				       y.s=y2; 
				       y.e=y1; 
					}
			        else 
					{
                       y.s=y1;
			  	       y.e=y2;
					}
				  }
		          else
				  {
					 if(x1>x2) 
					 {
					   midx=x1;
					   midy=y1;
					   x1=x2;
					   y1=y2;
					   x2=midx;
                       y2=midy;
					   if(sp==0) m=1;
					   else m=0;
					 }

                     if(fx>fy) 
					 {
				       if(m==0) 
					   {
					      x.pos=y1;
				 	      x.s=x1;
					      x.e=x2-fy;
					      if(y1<y2) 
						  { 
						    x_45.sx=x2-fy;
						    x_45.sy=y1;
						    x_45.ex=x2;
						    x_45.ey=y2;
						  }
					      else  
						  {
                            x_135.sx=x2-fy;
						    x_135.sy=y1;
						    x_135.ex=x2;
						    x_135.ey=y2;
						  }
					   }
				       else 
					   {
					     x.pos=y2;
					     x.s=x1+fy;
					     x.e=x2;
					     if(y1<y2)
						 {
                      	   x_45.sx=x1;
						   x_45.sy=y1;
						   x_45.ex=x1+fy;
						   x_45.ey=y2;
						 }
					     else
						 {
                           x_135.sx=x1;
						   x_135.sy=y1;
						   x_135.ex=x1+fy;
						   x_135.ey=y2;
						 }
					   }
					 }
				     else
					 {
                         if(m==0) 
						 {
					       y.pos=x1;
					       if(y1<y2)
						   {
					     	 x_45.sx=x1;
						     x_45.sy=y2-fx;
						     x_45.ex=x2;
						     x_45.ey=y2;
						     y.s=y1;
					         y.e=y2-fx;
						   }
					       else
						   { 
                             x_135.sx=x1;
						     x_135.sy=y2+fx;
						     x_135.ex=x2;
					      	 x_135.ey=y2;
					 	     y.s=y2+fx;
					         y.e=y1;
						   }
						 }
				         else
						 {
					         y.pos=x2;
					         if(y1<y2)
							 {
                             	x_45.sx=x1;
					          	x_45.sy=y1;
					        	x_45.ex=x2;
					          	x_45.ey=y1+fx;
					        	y.s=y1+fx;
				   	            y.e=y2;
							 }
					         else
							 {
                                x_135.sx=x1;
						        x_135.sy=y1;
						        x_135.ex=x2;
						        x_135.ey=y1-fx;
						        y.s=y2;
					            y.e=y1-fx;
							 }
						 }
					 }
				  } 
			  }
			  if(m==2||m==3)  
			  {
			       if(m==2)
				   {
				      x.pos=y2;
				      y.pos=x1; 
				   }
			       else 
				   {
			          x.pos=y1;
				      y.pos=x2;
				   }
			       if(x1>x2)
				   {
				      x.s=x2; 
				      x.e=x1; 
				   }
		           else
				   {
                      x.s=x1;
				      x.e=x2;
				   }
			       if(y1>y2)
				   {
				      y.s=y2; 
				      y.e=y1; 
				   }
			       else 
				   {
                      y.s=y1;
				      y.e=y2;
				   }
			  }
//			  if(i==4&&sp==0)
//				  printf("%.0lf %.0lf %.0lf\n",y.pos,y.s,y.e);
			  if(x.pos!=-1&&x.e!=-1&&x.s!=-1)
			  {
			    records2[i][sp].posh=x.pos;records2[i][sp].sh=x.s;records2[i][sp].eh=x.e;
			    records2[i][sp].mark[0]=true;
			  }
			  else records2[i][sp].mark[0]=false;
			  if(y.e!=-1&&y.pos!=-1&&y.s!=-1)
			  {
			    records2[i][sp].posv=y.pos;records2[i][sp].sv=y.s;records2[i][sp].ev=y.e;
			    records2[i][sp].mark[1]=true;
			  } 
			  else records2[i][sp].mark[1]=false;
			  if(x_45.sx!=999999999&&x_45.sy!=999999999&&x_45.ex!=999999999&&x_45.ey!=999999999)
			  {
			     records2[i][sp].pos45=P*(x_45.sy-x_45.sx);
			     records2[i][sp].s45=P*(x_45.sy+x_45.sx);
			     records2[i][sp].e45=P*(x_45.ey+x_45.ex);
				 records2[i][sp].mark[2]=true;
				 if(records2[i][sp].s45>records2[i][sp].e45)
				 {
				  midx=records2[i][sp].s45;
				  records2[i][sp].s45=records2[i][sp].e45;
				  records2[i][sp].e45=midx;
				 }
			  }
			  else records2[i][sp].mark[2]=false;
			  if(x_135.ex!=999999999&&x_135.ey!=999999999&&x_135.sx!=999999999&&x_135.sy!=999999999)
			  {
			     records2[i][sp].pos135=P*(x_135.sx+x_135.sy);
			     records2[i][sp].s135=P*(x_135.sy-x_135.sx);
			     records2[i][sp].e135=P*(x_135.ey-x_135.ex);
				 records2[i][sp].mark[3]=true;
				 if(records2[i][sp].s135>records2[i][sp].e135)
				 {
				  midy=records2[i][sp].s135;
				  records2[i][sp].s135=records2[i][sp].e135;
				  records2[i][sp].e135=midy;
				 }
			  }
			  else records2[i][sp].mark[3]=false;
             
			  for(k=1;k<=barr_num;k++)
			  {	             
				if(barr[k][0]>=r||barr[k][1]>=t||barr[k][2]<=l||barr[k][3]<=b) continue;

			    if(x.pos!=-1&&x.e!=-1&&x.s!=-1&&!(x.pos<=barr[k][1]||x.pos>=barr[k][3]||x.e<=barr[k][0]||x.s>=barr[k][2]))
				{
                   records1[i].serial_num[sp][records1[i].c[sp]]=k;				  
				   records1[i].c[sp]++;
				   records1[i].semiperimeter[sp]+=((barr[k][2]-barr[k][0])+(barr[k][3]-barr[k][1]));
				   continue;
				}

			    if(y.e!=-1&&y.pos!=-1&&y.s!=-1&&!(y.pos<=barr[k][0]||y.pos>=barr[k][2]||y.e<=barr[k][1]||y.s>=barr[k][3]))
				{
				   records1[i].serial_num[sp][records1[i].c[sp]]=k;
				   records1[i].c[sp]++;
				    records1[i].semiperimeter[sp]+=((barr[k][2]-barr[k][0])+(barr[k][3]-barr[k][1]));
				   continue;
				}
			    
			    if(x_45.sx!=999999999&&x_45.sy!=999999999&&x_45.ex!=999999999&&x_45.ey!=999999999)
				{
                   if((x_45.sx>barr[k][0]&&x_45.sx<barr[k][2]&&x_45.sy>barr[k][1]&&x_45.sy<barr[k][3])||(x_45.ex>barr[k][0]&&x_45.ex<barr[k][2]&&x_45.ey>barr[k][1]&&x_45.ey<barr[k][3]))
				   {
					  records1[i].serial_num[sp][records1[i].c[sp]]=k;
				      records1[i].c[sp]++;
					  records1[i].semiperimeter[sp]+=((barr[k][2]-barr[k][0])+(barr[k][3]-barr[k][1]));
				      continue; 				       
				   }
				   else
				   {
			         flag=0; 
			         cc=0;  
			         p=(x_45.ey-x_45.sy)/(x_45.ex-x_45.sx); 
			         q=x_45.sy-p*x_45.sx;
	                 
                     crop=(barr[k][1]-q)/p; 
			         if(crop>=barr[k][0]&&crop<=barr[k][2]&&crop>=x_45.sx&&crop<=x_45.ex) 
					 { 
			     	    flag++; 
				        if(cc<2)
						{ 
				           cro_point[cc][0]=crop;
				           cro_point[cc++][1]=barr[k][1];
						}
					 }
			         crop=(barr[k][3]-q)/p;
			         if(crop>=barr[k][0]&&crop<=barr[k][2]&&crop>=x_45.sx&&crop<=x_45.ex) 
					 { 
			    	    flag++;
			            if(cc<2)
						{
			               cro_point[cc][0]=crop;
			               cro_point[cc++][1]=barr[k][3];
						}
					 }
		             crop=p*barr[k][0]+q;
			         if(crop>=barr[k][1]&&crop<=barr[k][3]&&crop>=x_45.sy&&crop<=x_45.ey)
					 {
				       flag++;
				       if(cc<2)
					   {
				         cro_point[cc][0]=barr[k][0];
				         cro_point[cc++][1]=crop;
					   }
					 }
			         crop=p*barr[k][2]+q;
			         if(crop>=barr[k][1]&&crop<=barr[k][3]&&crop>=x_45.sy&&crop<=x_45.ey)
					 {
				       flag++;
				       if(cc<2)
					   {
					     cro_point[cc][0]=barr[k][2];
				         cro_point[cc++][1]=crop;
					   }
					 }
			         if(flag==3||flag==4)
					 {
					  records1[i].serial_num[sp][records1[i].c[sp]]=k;
				      records1[i].c[sp]++;
					  records1[i].semiperimeter[sp]+=((barr[k][2]-barr[k][0])+(barr[k][3]-barr[k][1]));
				      continue; 
					 }
			         
					 if(flag==2)
					 { 
                        if(!(cro_point[0][0]==cro_point[1][0]&&cro_point[0][1]==cro_point[1][1]))
						{
						   records1[i].serial_num[sp][records1[i].c[sp]]=k;
				           records1[i].c[sp]++;
						   records1[i].semiperimeter[sp]+=((barr[k][2]-barr[k][0])+(barr[k][3]-barr[k][1]));
				           continue; 
						}
					 }
				   }

				}
				if(x_135.ex!=999999999&&x_135.ey!=999999999&&x_135.sx!=999999999&&x_135.sy!=999999999)
				{
                   if((x_135.sx>barr[k][0]&&x_135.sx<barr[k][2]&&x_135.sy>barr[k][1]&&x_135.sy<barr[k][3])||(x_135.ex>barr[k][0]&&x_135.ex<barr[k][2]&&x_135.ey>barr[k][1]&&x_135.ey<barr[k][3])) //如果135度斜边有一个顶点在矩形内，则肯定相交
				   {
					  records1[i].serial_num[sp][records1[i].c[sp]]=k;
				      records1[i].c[sp]++;
					  records1[i].semiperimeter[sp]+=((barr[k][2]-barr[k][0])+(barr[k][3]-barr[k][1]));
				      continue; 		       
				   }
			       else
				   {
			         flag=0; 
			         cc=0;  
			         p=(x_135.ey-x_135.sy)/(x_135.ex-x_135.sx); 
			         q=x_135.sy-p*x_135.sx;
		            
                     crop=(barr[k][1]-q)/p; 
			         if(crop>=barr[k][0]&&crop<=barr[k][2]&&crop>=x_135.sx&&crop<=x_135.ex) 
					 { 
			           flag++; 
			           if(cc<2)
					   {
			            cro_point[cc][0]=crop;
				        cro_point[cc++][1]=barr[k][1];
					   }
					 }
			         crop=(barr[k][3]-q)/p;
			         if(crop>=barr[k][0]&&crop<=barr[k][2]&&crop>=x_135.sx&&crop<=x_135.ex) 
					 {
				        flag++;
				        if(cc<2)
						{
				         cro_point[cc][0]=crop;
			             cro_point[cc++][1]=barr[k][3];
						}
					 }
		             crop=p*barr[k][0]+q;
			         if(crop>=barr[k][1]&&crop<=barr[k][3]&&crop>=x_135.ey&&crop<=x_135.sy)
					 { 
				        flag++;
				        if(cc<2)
						{
			               cro_point[cc][0]=barr[k][0];
				           cro_point[cc++][1]=crop;
						}
					 }
			        crop=p*barr[k][2]+q;
			        if(crop>=barr[k][1]&&crop<=barr[k][3]&&crop>=x_135.ey&&crop<=x_135.sy)
					{
				        flag++;
				        if(cc<2)
						{
				            cro_point[cc][0]=barr[k][2];
				            cro_point[cc++][1]=crop;
						}
					}
		      	    if(flag==3||flag==4)
					{
					  records1[i].serial_num[sp][records1[i].c[sp]]=k;
				      records1[i].c[sp]++;
					  records1[i].semiperimeter[sp]+=((barr[k][2]-barr[k][0])+(barr[k][3]-barr[k][1]));
				      continue; 
					}
			        if(flag==2)
					{ 
                      if(!(cro_point[0][0]==cro_point[1][0]&&cro_point[0][1]==cro_point[1][1])) 
					  { 
						 records1[i].serial_num[sp][records1[i].c[sp]]=k;
				         records1[i].c[sp]++;
						 records1[i].semiperimeter[sp]+=((barr[k][2]-barr[k][0])+(barr[k][3]-barr[k][1]));
				         continue; 
					  }
					}
				   }
				}
			 }
		  }
     }
//   printf("%d %d %d %d\n",records2[4][0].mark[0],records2[4][0].mark[1],records2[4][0].mark[2],records2[4][0].mark[3]);
//	for(i=1;i<vertice;i++)
//	{
//	   printf("edge%d:\n",i);
//	   for(j=0;j<4;j++)
//	   {
//	     printf("方式%d穿%d:",j,records1[i].c[j]);	
//	     for(k=0;k<records1[i].c[j];k++)
//		 {
//		    printf("%d ",records1[i].serial_num[j][k]);
//		 }
//		   printf("\n");
//	   }
//	}
}